src/onlineform/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static

from reflect.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^stunion/',include('reflect.urls')),
    url(r'^success/', success, name='sucess'),
    url(r'^accounts/', include('registration.backends.default.urls')),   #DJANGO REGISTRATION REDUX
]

if settings.DEBUG:
    urlpatterns+=(static(settings.STATIC_URL,document_root=settings.STATIC_ROOT))

src/reflect/urls.py
from django.conf.urls import url
from reflect.views import *

urlpatterns = [
	#url(r'^$',ReflectionDetailView.as_view(), name="list"),
    url(r'^$', ReflectionListView.as_view(), name='list'),
    url(r'^important/$', ReflectionListViewImportant.as_view(), name='important'),
    url(r'^(?P<pk>\d+)/$',ReflectionDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/delete/$',ReflectDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/mark/$',markImportant, name='mark'),
]

src/reflect/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.


class Reflection(models.Model):
	name = models.CharField(max_length=50, blank = True, null = True)
	email = models.EmailField()

	CATEGORY_CHOICES = [
        ("FACILITY", "學校設備"),
        ("RESTAURANT", "餐廳食物"),
        ("ACADEMY", "課業學習"),
        ("ACTIVITY", "學生活動"),
        ("OTHER", "其他"),
    ]
	category = models.CharField(max_length=10, choices= CATEGORY_CHOICES)
	content = models.TextField(max_length=500, blank = False, null = True)
	advice = models.TextField(max_length=500, blank = True, null = True)
	timestamp = models.DateTimeField(auto_now=True)
	state = models.IntegerField(default = 0)
	important = models.BooleanField(default=False)
	#replies = models.ManyToManyField(Reply)

	def __str__(self):
		return str(self.timestamp)

class Reply(models.Model):
	user = models.CharField(max_length = 20) # 回覆的使用者
	content = models.CharField(max_length = 500) # 回覆內容
	timestamp = models.DateTimeField(auto_now=True) # 創建時間
	reflection = models.ForeignKey(Reflection, on_delete=models.CASCADE, default=None, null=True)
	#reflectionID = models.IntegerField(unique=True) # 該問題的id
	def __str__(self):
		return str(self.timestamp)

src/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<!--黑體-->
	<style type="text/css">
		@import url(http://fonts.googleapis.com/earlyaccess/cwtexhei.css);
		.google-font{
			font-family: 'cwTeXHei', sans-serif;
		}
	</style>
    {% block header%}
    {% endblock %}
	</head>
    <body>
    <div class="google-font">
    {% block content %}
    {% endblock %}
    </div>
    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

src/templates/dashboard-base.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>學聯會問題後台</title>
  
  
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'>
    <link rel="stylesheet" href="{% static 'css/dashboard-style.css' %}">


    {% block header%}
    {% endblock %}  
</head>

<body>
  
<div id="nav">
  <div class="user-banner">
    <h5 class="username">{{ user.username }}</h5>
  </div>
  <ul>
    <li class="head">功能</li>
    {% if request.path == '/stunion/' %}<li class="active"> {% else %} <li> {% endif %}<a href="{% url 'list' %}"><i class="fa fa-fw fa-inbox"></i><span class="swatch light-grey">Inbox</span></a></li>
    {% if request.path == '/stunion/important/' %}<li class="active"> {% else %} <li> {% endif %}<a href="{% url 'important' %}"><i class="fa fa-fw fa-star"></i><span>標記重要</span></a></li>
    <li><a href="{% url 'auth_logout' %}"><i class="fa fa-fw fa-user"></i><span>登出<span></a></li>
  </ul>
</div>
<div id="main">
{% block content %}
{% endblock %}
</div>
    <script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js'></script>
    <script src="js/index.js"></script>

</body>
</html>

src/templates/delete_confirm.html
{% extends "dashboard-base.html" %}
{% load i18n %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>你確定要刪除這則意見嗎?</p>
    <p>
	時間：{{object.timestamp}}</br>
	姓名：{{object.name}}</br>
	email:{{object.email}}</br>
	類別：{{object.category}}</br>
	內容：{{object.content}}</br>
	建議：{{object.advice}}
	</p>
    <input type="submit" value="確定" />
    <a href="{% url 'list' %}"><input type="button" name="Cancel" value="取消"></a>
</form>
{% endblock %}

src/templates/detail.html
{% extends "dashboard-base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

{% if request.user.is_authenticated %}
  <header>
    <ol class="breadcrumb">
      <li> <a href="{% url 'list' %}">問題列表</a></li>
      <li class="active">問題詳情</li>
    </ol>
  </header>
  <div id="content">
    <h1>學聯會回饋管理頁面</h1>
    <div class="box">
      <div class="body">
      		<div class="row">
      			<div class="col-sm-3">電子郵件 <p>{{ email }}</p></div>
      			<div class="col-sm-2">類別 <p>{{ category }}</p></div>
      			<div class="col-sm-3">表單填寫時間<p>{{ timestamp }}</p></div>
      			<div class="col-sm-2">
      				狀態
      				<p>
      				{% if state == 0 %}
						未讀
					{% elif state == 1 %}
						處理中
					{% elif state == 2 %}
						已完成
					{% endif %}
      				</p>
      			</div>
      			<div class="col-sm-2">		
      			{% if not state == 2 %}
					<form method="POST" action="">{% csrf_token %}	
						<input type="submit" name="Finish" value="標記成已完成" class="btn btn-detail">
					</form>
				{% endif %}
				<a href="{% url 'list' %}"><input type="button" class="btn btn-detail" name="Return" value="回清單"></a>
				</div>
      		</div>
		<hr>
		<div class="questions-box">
			<h2>意見描述</h2>
			<span>{{ content  }}</span>
			<h2>建議方向</h2>
			<span>{{ advice }}</span>
		</div>
		<hr>
		{% if not state == 2%}
		<form method="POST" action="" class="form">{% csrf_token %}
			<p>{{  form.user.label }}</p>
			<p>{{ form.user }}</p>	
	
			<p>{{ form.content.label}}</p>
			<div class="row">
				<div class="col-sm-10">
					{{ form.content }}					
				</div>
				<div class="col-sm-2">
					<input type="submit" name="Reply" value="送出" class="btn btn-detail">
				</div>
		</form>
		{% endif %}

		<table class="table">
			<tr>
				<td>回覆人</td>
				<td>回覆時間</td>
				<td>回覆內容</td>
			</tr>
			{% for reply in replies %}
			<tr>
				<td>{{  reply.user }}</td>
				<td>{{  reply.timestamp }}</td>
				<td>{{ reply.content }}</td>
			</tr>
			{% empty %}
			<tr>
				<td>未有任何回覆</td>
				<td>無</td>
			</tr>
			{%  endfor %}
		</table>
		</div>
	</div>
</div>	
	
{% endif %}
{% endblock %}

src/templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/angular-material.css'%}">
	<link rel="stylesheet" type="text/css" href="https://material.angularjs.org/1.1.1/docs.css">	
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

<h1 class="text-align-center">{{title}}</h1>
<div class="row">
<div ng-controller="formCtrl" ng-cloak="" class="checkboxSyncing col-md-10 col-md-offset-1" ng-app="MyApp">
	<form method="POST" action="" name="userForm">{% csrf_token %}
		<md-content layout-padding="">
			<div layout-gt-sm="row">
				<md-input-container flex-gt-sm="" class="md-block">
					<label>電郵</label>
					<input ng-model="user.email" name="email" id="email" minlength="10" maxlength="100" required = "" ng-pattern="/^.+@.+\..+$/" type="email">
					<div ng-messages="userForm.email.$error" role="alert">
	<!-- 					<div ng-messages-exp="['required' , 'minlength','maxlength','pattern']" ></div> -->
						<div ng-message="required">
							我們需要您的電郵來與您聯繫
						</div>
						<div ng-message="pattern">
							你的電郵需要長得想電郵才行...
						</div>
						<div ng-message="maxlength">
							電郵長度必須小於 100個字
						</div>		
						<div ng-message="minlength">
							電郵長度必須小於 10個字
						</div>
					</div>
				</md-input-container>
			</div>
			<div layout-gt-sm="row">
				<md-input-container flex-gt-sm="" class="md-block">
					<label>姓名</label>
					<input ng-model="user.name" name="name" id="name" minlength="2" maxlength="100" >
					<div class="hint" ng-if="showHints">我們該如何稱呼你？</div>
				</md-input-container>
			</div>
			<div layout-gt-sm="row" >
				<div flex-gt-sm="30">
					<label>請問您的議題是關於什麼類別</label>
					<md-select ng-model="user.category" placeholder="問題類別" class="md-no-underline" required="" md-no-asterisk="false">
					    <md-option value="FACILITY">學校設備</md-option>
					    <md-option value="RESTAURANT">餐廳食物</md-option>
					    <md-option value="ACADEMY">課業學習</md-option>
					    <md-option value="ACTIVITY">學生活動</md-option>
					    <md-option value="OTHER">其他</md-option>
					</md-select>
					<input ng-model="user.category" name="category" id="category" minlength="10" maxlength="100" style="display:none;">
				</div>
	  		</div>
			<div layout-gt-sm="row">
				<md-input-container flex-gt-sm="" class="md-block">
					<label>意見內容</label>
					<textarea ng-model="user.content" name="content" id="content"  md-maxlength="500" rows="5" md-select-on-focus="" required=""></textarea>
					<div ng-messages="userForm.content.$error">
						<div ng-message="required">
							您必須填寫議題內容
						</div>
					</div>
				</md-input-container>	
			</div>
			<div layout-gt-sm="row">
				<md-input-container flex-gt-sm="" class="md-block">
					<label>建議</label>
					<textarea ng-model="user.suggestions" name="suggestion" id="suggestion"  md-maxlength="500" rows="5" md-select-on-focus="" ></textarea>
					<div class="hint" ng-if="showHints">
						<!-- some hints message here -->
					</div>
				</md-input-container>	
			</div>

			<div layout-gt-sm="row" class="text-align-center" layout-align="center center" >
				<md-button type="submit" class="md-raised md-warn">送出</md-button>
			</div>
		</md-content>
	<!-- {{form.as_p}} -->
	</form>
	</div>

</div>
	<footer>
		<a href="{% url 'auth_login' %}">學聯會登入</a>
	</footer>
	<script type="text/javascript" src="{% static 'js/angular.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/angular-route.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/angular-aria.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/angular-animate.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/home.js' %}"></script>
	<script src="{% static 'js/angular-messages.min.js' %}"></script>
	<script src="{% static 'js/svg-assets-cache.js' %}"></script>
	<script src="{% static 'js/angular-material.js' %}"></script>
{% endblock %}

src/templates/stunion.html
{% extends "dashboard-base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
{% if request.user.is_authenticated %}
  <header>
    <ol class="breadcrumb">
      <li class="active">問題列表</li>
    </ol>
  </header>
  <div id="content">
    <h1>學聯會回饋管理頁面</h1>
    <div class="box">
      <div class="body">
      		<div class="row">
				<div class="col-md-8 status-row">
					<span class="status-unread" ></span><p>未讀取</p>
					<span class="status-handling"></span><p>處理中</p>
					<span style="" class="status-finished"></span><p>已完成</p>
				</div>
				<div class="col-md-4">
					<form action="" method="post">{% csrf_token %}	
						<select  name="list_selector" > 
							<option value="all">全</option>
							<option value="unread">未讀取</option>
							<option value="handling">處理中</option>
							<option value="finished">已完成</option>
						</select>
					<input type="submit" name="selector" class="btn-filter"value="篩選"/>
					</form>
				</div>
			</div>
			<div>
				<table class='table'>
					{% if reflection_list %}
						<tr>
							<td></td>
							<td>時間</td>
							<td>名字</td>
							<td>信箱</td>
							<td>類別</td>
							<td>內容</td>
							<td>建議</td>
							<td>詳細</td>
							<td>刪除</td>
						</tr>

						{% for object in reflection_list %}
							{% if object.state == 0 %}
							<tr class="unread_reflection" bgcolor="FFA69E">
							{% elif object.state == 1 %}
							<tr class="read_reflection" bgcolor="B8F2E6">
							{% elif object.state == 2 %}
							<tr class="finished_reflection" bgcolor="FAF3DD">
							{% else %}
							<tr>
							{% endif %}

							<td>
								<a href='/stunion/{{object.id}}/mark'>
								{% if object.important %}
									<i class="fa fa-star"></i>
								{% else %}
									<i class="fa fa-star-o"></i>
								{% endif %}
								</a>
<!-- 								{% if object.state == 0 %}
								狀態：未讀
								{% elif object.state == 1 %}
								狀態：處理中
								{% elif object.state == 2 %}
								狀態：已完成
								{% else %}
								狀態 ：
								{% endif %} -->
							</td>
							<td>{{object.timestamp}}</td>
							<td>{{object.name}}</td>
							<td>{{object.email}}</td>
							<td>
							{% if object.category == 'ACADEMY' %}
							<i class="fa fa-book" aria-hidden="true"></i>
							{% elif object.category == 'RESTAURANT' %}
							<i class="fa fa-spoon" aria-hidden="true"></i>
							{% elif object.category == 'FACILITY' %}
							<i class="fa fa-child" aria-hidden="true"></i>
							{% elif object.category == 'ACTIVITY' %}
							<i class="fa fa-child" aria-hidden="true"></i>
							{% else %}
							其他
							{% endif %}
							</td>

							<td>{{object.content|slice:":10"}}</td>
							<td>{{object.advice|slice:":10" }}</td>
							<td><a href='/stunion/{{object.id}}'>詳細</a></td>
							<td><a href='/stunion/{{object.id}}/delete'>刪除</a></td>
							</tr>					
						{% endfor %}
					{% else %}
						<tr><td>沒有任何意見喔</td></tr>	
					{% endif %}

				</table>
		</div>
    </div>
	</div>
</div>
{% endif %}
{% endblock %}

src/templates/success.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/angular-material.css'%}">
	<link rel="stylesheet" type="text/css" href="https://material.angularjs.org/1.1.1/docs.css">	
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}
<div class="row boxing"> 
	<div class="col-md-8 col-md-offset-2 ">
		<h1>繳交成功！</h1>
		<p>福利部收到您的問題了，我們將會努力地解決它迪～</p>
	</div>
</div>
	<footer>
		<a href="{% url 'auth_login' %}">學聯會登入</a>
	</footer>
{% endblock %}